version: "3"

x-env: &env
  environment:
    POSTGRES_URL: "postgresql://postgres:postgres@postgres:5432/postgres?schema=public"
    CLICKHOUSE_URL: "http://clickhouse:8123"
    REDIS_URL: "redis://redis:6379"
    NODE_ENV: "production"
  env_file:
    - path: .env
      required: false

services:
  redis:
    extends:
      file: docker-compose.base.yml
      service: redis

  postgres:
    extends:
      file: docker-compose.base.yml
      service: postgres

  clickhouse:
    extends:
      file: docker-compose.base.yml
      service: clickhouse

  consumer:
    build:
      context: .
      dockerfile: ./consumer/Dockerfile
    depends_on:
      postgres:
        condition: service_started
      clickhouse:
        condition: service_started
      redis:
        condition: service_started
      migrator:
        condition: service_completed_successfully
    <<: *env

  dashboard:
    build:
      context: .
      dockerfile: ./dashboard/Dockerfile
    restart: on-failure
    depends_on:
      postgres:
        condition: service_started
      clickhouse:
        condition: service_started
      migrator:
        condition: service_completed_successfully
    ports:
      - "3000:3000"
    <<: *env

  migrator:
    build:
      context: .
      dockerfile: ./packages/databases/Dockerfile
    depends_on:
      postgres:
        condition: service_started
      clickhouse:
        condition: service_started
    command: sh -c "cd packages/databases && npx prisma generate && npx prisma migrate deploy && npx prisma db seed && npx tsx src/clickhouse.ts"
    <<: *env

volumes:
  postgres_data:
  redis_data:
  clickhouse_data:
