version: "3"

services:
  redis:
    extends:
      file: docker-compose.base.yml
      service: redis

  postgres:
    extends:
      file: docker-compose.base.yml
      service: postgres

  clickhouse:
    extends:
      file: docker-compose.base.yml
      service: clickhouse

  consumer:
    build:
      context: .
      dockerfile: ./consumer/Dockerfile
    depends_on:
      - postgres
      - clickhouse
      - redis
    environment:
      POSTGRES_URL: "postgresql://postgres:postgres@postgres:5432/postgres?schema=public"
      CLICKHOUSE_URL: "http://clickhouse:8123"
      REDIS_URL: "redis://redis:6379"
      NODE_ENV: "production"

  dashboard:
    build:
      context: .
      dockerfile: ./dashboard/Dockerfile
    restart: on-failure
    depends_on:
      - postgres
      - clickhouse
    environment:
      POSTGRES_URL: "postgresql://postgres:postgres@postgres:5432/postgres?schema=public"
      CLICKHOUSE_URL: "http://clickhouse:8123"
      REDIS_URL: "redis://redis:6379"
      NODE_ENV: "production"
    ports:
      - "3000:3000"

  migrator:
    build:
      context: .
      dockerfile: ./packages/databases/Dockerfile
    depends_on:
      - clickhouse
      - postgres
    command: sh -c "cd packages/databases && npx prisma generate && npx prisma migrate deploy && npx prisma db seed && npx tsx src/clickhouse.ts"
    environment:
      POSTGRES_URL: "postgresql://postgres:postgres@postgres:5432/postgres?schema=public"
      CLICKHOUSE_URL: "http://clickhouse:8123"
      REDIS_URL: "redis://redis:6379"
      NODE_ENV: "production"

volumes:
  postgres_data:
  redis_data:
  clickhouse_data:
