import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
import { Navbar } from "../components/Navbar";
import { Panel } from "~/components/ui/custom/panel";

function Datasets() {
  const { data: datasets } = api.datasets.list.useQuery();

  return (
    <div className="p-8">
      <h1 className="text-lg text-emphasis-foreground">Datasets</h1>
      <div className="h-8"></div>
      <div className="flex flex-col gap-4">
        {datasets?.map((dataset) => (
          <Link key={dataset.id} href={`/${dataset.id}/events`}>
            <Panel className="transition hover:bg-muted text-lg">
              {dataset.description}
            </Panel>
          </Link>
        ))}
      </div>
    </div>
  );
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Datasets />
    </>
  );
}
