import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
import { Navbar } from "../components/Navbar";
import { Card, Text, Title } from "@tremor/react";

function Datasets() {
  const { data: datasets } = api.datasets.list.useQuery();

  return (
    <div className="p-8">
      <Title>Datasets</Title>
      <div className="h-8"></div>
      <div className="flex flex-col gap-4">
        {datasets?.map((dataset) => (
          <Link key={dataset.id} href={`/datasets/${dataset.id}/events`}>
            <Card className="transition hover:bg-gray-50">
              <Title>{dataset.name}</Title>
              <Text>{dataset.description}</Text>
            </Card>
          </Link>
        ))}
      </div>
    </div>
  );
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Datasets />
    </>
  );
}
