export const env = {
  NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN: process.env.NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN,
  MAXMIND_ACCOUNT_ID: process.env.MAXMIND_ACCOUNT_ID,
  MAXMIND_LICENSE_KEY: process.env.MAXMIND_LICENSE_KEY,
};
